spring.application.name=recipes-api

spring.datasource.url=jdbc:postgresql://localhost:5432/recipes-api-db
spring.datasource.username=recipes-api-db
spring.datasource.password=recipes-api-db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false